# Generated by Django 2.0.7 on 2018-07-31 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateTimeField()),
                ('addr', models.CharField(max_length=100)),
                ('network', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateTimeField()),
                ('chan_id', models.CharField(max_length=20)),
                ('last_update', models.IntegerField()),
                ('capacity', models.BigIntegerField()),
                ('chan_point', models.CharField(max_length=67)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('dataset_type', models.CharField(default="'scatter'", max_length=100)),
                ('dataset_labels', models.CharField(blank=True, max_length=999)),
                ('dataset_options', models.CharField(blank=True, max_length=999)),
                ('dataset_url', models.CharField(max_length=250)),
                ('image_url', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodes.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateTimeField()),
                ('last_update', models.IntegerField()),
                ('pub_key', models.CharField(max_length=67)),
                ('alias', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('channels', models.IntegerField()),
                ('capacity', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node_Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateTimeField()),
                ('time_lock_delta', models.IntegerField()),
                ('min_htlc', models.IntegerField()),
                ('fee_base_msat', models.IntegerField()),
                ('fee_rate_milli_msat', models.IntegerField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.Channel')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.Node')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('date_logged', 'pub_key')},
        ),
        migrations.AddField(
            model_name='channel',
            name='node1_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node1_pub', to='nodes.Node'),
        ),
        migrations.AddField(
            model_name='channel',
            name='node2_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node2_pub', to='nodes.Node'),
        ),
        migrations.AddField(
            model_name='address',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.Node'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('date_logged', 'chan_id')},
        ),
    ]
