# Generated by Django 2.0.5 on 2018-06-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateTimeField()),
                ('addr', models.CharField(max_length=20)),
                ('network', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateTimeField()),
                ('chan_id', models.CharField(max_length=20)),
                ('last_update', models.IntegerField()),
                ('capacity', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateTimeField()),
                ('last_update', models.IntegerField()),
                ('pub_key', models.CharField(max_length=67)),
                ('alias', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('channels', models.IntegerField()),
                ('capacity', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node_Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateTimeField()),
                ('time_lock_delta', models.IntegerField()),
                ('min_htlc', models.IntegerField()),
                ('fee_base_msat', models.IntegerField()),
                ('fee_rate_milli_msat', models.IntegerField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.Channel')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.Node')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('date_logged', 'pub_key')},
        ),
        migrations.AddField(
            model_name='channel',
            name='node1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node1', to='nodes.Node'),
        ),
        migrations.AddField(
            model_name='channel',
            name='node2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node2', to='nodes.Node'),
        ),
        migrations.AddField(
            model_name='address',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.Node'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('date_logged', 'chan_id')},
        ),
    ]
