# Generated by Django 2.0.5 on 2018-06-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_auto_20180622_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addr',
            field=models.CharField(max_length=49),
        ),
    ]
