# Generated by Django 2.0.5 on 2018-06-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0006_auto_20180623_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='chan_point',
            field=models.CharField(default='N/A', max_length=67),
            preserve_default=False,
        ),
    ]
